version: "3"
services:
  frontend:
    image: node:16
    volumes:
      - ./frontend:/app
      - ./docs/posts:/app/public/posts
      - ./docs/meta.json:/app/public/meta.json
      - ./docs/sitemap.xml:/app/public/sitemap.xml

    working_dir: /app
    entrypoint: yarn start
    tty: true
    ports:
      - 3000:3000
