name: Github blog update slack nofify

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      URL: unknownpgr.com

    steps:
      - name: Send message
        run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"Github blog updated! : ${{env.URL}}"}' \"${{secrets.SLACK_KEY}}\""

