name: Github blog auto update

on:
  push:
    branches: [master]

jobs:
  update-build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '[build]')
    env:
      USER_NAME: unknownpgr
      USER_EMAIL: unknownpgr@gmail.com
      BLOG_URL: unknownpgr.com

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache frontend node node_modules
        uses: actions/cache@v1
        with:
          path: frontend/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('frontend/yarn.lock') }}

      - name: Cache backend node_modules
        uses: actions/cache@v1
        with:
          path: backend/node_modules
          key: ${{ runner.OS }}-update-${{ hashFiles('backend/yarn.lock') }}

      - name: Initialize frontend
        working-directory: frontend
        run: yarn install

      - name: Initialize backend
        working-directory: backend
        run: yarn install

      - name: Update posts
        working-directory: backend
        run: node blog.js

      - name: Build blog
        working-directory: frontend
        run: yarn build

      - name: Commit updated posts
        run: |
          git add .
          if [[ `git status --porcelain` ]]; then
            git config --local user.email ${{env.USER_EMAIL}}
            git config --local user.name ${{env.USER_NAME}}
            git add .
            git commit -m "Auto blog update at $(date)"
          fi

      - name: Push updated posts
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build fail
        run: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text":"Github blog build failed."}'' "${{secrets.SLACK_KEY}}"'
        if: failure()

      - name: Make a new directory
        run: mkdir ../blog-publish

      - name: Git init
        working-directory: ../blog-publish
        run: |
          git init
          git remote add origin https://github.com/${{env.USER_NAME}}/${{env.USER_NAME}}.github.io.git
          git pull origin master

      - name: Update fail
        run: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text":"Github blog update failed."}'' "${{secrets.SLACK_KEY}}"'
        if: failure()

      - name: Copy build
        run: |
          rm -rf ../blog-publish/*
          yes | cp -rf frontend/build/* ../blog-publish
          yes | cp -rf  backend/build/* ../blog-publish
          yes | cp -rf root/. ../blog-publish
          echo "Copied."

      - name: Commit
        working-directory: ../blog-publish
        run: |
          git config --global user.email ${{env.USER_EMAIL}};
          git config --global user.name ${{env.USER_NAME}};
          git add .
          git diff-index --quiet HEAD || git commit -m "Update frontend at $(date).";
          remote_repo="https://${USER_NAME}:${{ secrets.ACCESS_TOKEN }}@github.com/${{env.USER_NAME}}/${{env.USER_NAME}}.github.io.git"
          git push "${remote_repo}" HEAD:master;

      - name: Update Success
        run: 'curl -X POST -H ''Content-type: application/json'' --data ''{"text":"Github blog update succeed. ${{env.BLOG_URL}}"}'' "${{secrets.SLACK_KEY}}"'
